apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testproject
  template:
    metadata:
      labels:
        app: testproject
    spec:
      containers:
      - name: testproject
        image: "docker.io/bhavya762/testproject:latest"  
        ports:
        - containerPort: 8080
