apiVersion: batch/v1
kind: Job
metadata:
  name: testproject-job  # Name reflects it's a Job, not a Deployment
spec:
  template:
    metadata:
      labels:
        app: testproject
    spec:
      containers:
      - name: testproject
        image: bhavya762/testproject:latest  # Ensure this image is accessible in your container registry
        imagePullPolicy: Always             # Ensures the latest image is pulled (optional)
      restartPolicy: Never                  # Ensures the pod doesn't restart if it completes or fails
  backoffLimit: 4                           # Retries 4 times in case of failure
