apiVersion: batch/v1
kind: Job
metadata:
  name: testproject-job  # Name reflects it's a Job, not a Deployment
spec:
  template:
    metadata:
      labels:
        app: testproject
    spec:
      containers:
      - name: testproject
        image: bhavya762/testproject:latest  
        imagePullPolicy: Always             
      restartPolicy: Never                  
  backoffLimit: 4                           
